version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies....."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "zipping deployment package...."
      - cd lib
      - zip -r9 ..deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "uploading to s3..."
      - aws s3 cp deployment_package.zip s3://aws-boot-cicd-bucket/
      - aws lambda update-function-code --function-name test-cicd --s3-bucket aws-boot-cicd-bucket --s3-key deployment_package.zip
      - echo "Deployment complete !!!!!!!!"


